#!/bin/bash

RECEIVERPORT=1234
SERVERPORT=4321
LOGFILE=/tmp/debugserver.log
LINES=200
SERVERPIDFILE=/tmp/debugserver.pid
RECEIVERPIDFILE=/tmp/debugreceiver.pid

case $1
in
    debugreceiver)

        while true;
        do
            # test ist logfile exists and append incoming messages to it
            [ ! -f $LOGFILE ] && touch $LOGFILE
            nc -l $RECEIVERPORT >> $LOGFILE
            # shorten it to the last lines, the quotation maks will keep the special characters like '\n' etc.
            echo "`tail -n $LINES $LOGFILE`" > $LOGFILE
        done
    ;;


    debugserver)

        while true;
        do
        {
            echo -e 'HTTP/1.1 200 OK';
            echo -e 'Content-Type: text/html; charset=UTF-8\n';
            echo -e '<html>';
            echo -e '<head>';
            echo -e '<meta http-equiv="Content-Language" content="de">';
            echo -e '<meta http-equiv="refresh" content="2">';
            echo -e '<title>HTML Debug Server</title>';
            echo -e '</head>';
            echo -e '<body style="background-color:gray;">';
            echo -e '<h1>';
            echo -e 'Debug Server';
            echo -e '</h1>';
            echo -e '<pre>';
            cat $LOGFILE;
            echo -e '</pre>';
            echo -e '<script>';
            echo -e 'window.scrollTo( 0, document.body.scrollHeight );';
            echo -e '</script>';
            echo -e '</body>';
            echo -e '</html>';
        } | nc -l $SERVERPORT -q 0;
        done
    ;;

    start)

        $0 debugserver &> /dev/null &
        jobs -p > $SERVERPIDFILE
        disown %1

        $0 debugreceiver &> /dev/null &
        jobs -p > $RECEIVERPIDFILE
        disown %1

        echo "Server has been started..."
    ;;

    stop)

        unset PID
        read PID < $RECEIVERPIDFILE
        rm -f $RECEIVERPIDFILE
        kill $PID

        unset PID
        read PID < $SERVERPIDFILE
        rm -f $SERVERPIDFILE
        kill $PID

        echo "Server has been stopped..."
    ;;

    *)

        echo "Usage: $0 start | stop"
    ;;
esac


